version: "3.9"

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    
    image: backend
    container_name: backend

    ports:
      - 8000:8000
    volumes:
      - ./backend:/app

  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend

    ports:
      - 8501:8501
    volumes:
      - ./frontend:/app


